{% set name = "viresclient" %}
{% set version = "0.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/viresclient-{{ version }}.tar.gz
  sha256: 047255b7743ef7a61761b796334737a216107439e641f251eb20d3a7d1bca1ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - viresclient = viresclient.commands.viresclient:start

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - cdflib >=0.3.20
    - jinja2 >=2.10
    - netcdf4 >=1.5.3
    - pandas >=0.18
    - requests >=2.0.0
    - pytables >=3.4.4
    - tqdm >=4.23.0
    - xarray >=0.11.0

test:
  imports:
    - viresclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ESA-VirES/VirES-Python-Client/
  summary: A Python client for interacting with a VirES server
  license: MIT
  license_file: LICENSE
  doc_url: https://viresclient.readthedocs.io/

extra:
  recipe-maintainers:
    - smithara
