{% set name = "viresclient" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/viresclient-{{ version }}.tar.gz
  sha256: 2918f1ff84b38f9cf6c041e7788d60cd4e2a51d72d8f3e542d9cd31948d41ff2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - viresclient = viresclient.commands.viresclient:start

requirements:
  host:
    - python >=3.6
    - pip
    - flit
  run:
    - python >=3.6
    - cdflib >=0.3.20
    - jinja2 >=2.10
    - netcdf4 >=1.5.3
    - pandas >=0.18
    - requests >=2.0.0
    - pytables >=3.4.4
    - tqdm >=4.23.0
    - xarray >=0.11.0

test:
  imports:
    - viresclient
  # commands:
  #   - pip check  # skip until cdflib package fixed
  requires:
    - pip

about:
  home: https://github.com/ESA-VirES/VirES-Python-Client/
  summary: A Python client for interacting with a VirES server
  license: MIT
  license_file: LICENSE
  doc_url: https://viresclient.readthedocs.io/

extra:
  recipe-maintainers:
    - smithara
